alias gs='git status '
alias ga='git add '
alias gb='git branch '
alias gc='git commit -m'
alias gd='git diff'
alias gco='git checkout '
alias gk='gitk --all&'
alias gx='gitx --all'
alias gl='git log --pretty=format:"%h %ad | %s%d [%an]" --graph --date=short'
alias gt='git tag'
alias gpl='git pull --rebase'
alias gp='git push'

alias got='git '
alias get='git '
alias gca='git commit --amend -m' 
alias pd='pwd'
